Write a function to compute 5/0 and use try/except to catch the exceptions.

In [11]:
def division(divid,divis):
    try:
        ans=(float(divid/divis))
        return ans
    except ZeroDivisionError:
        print("Please enter a number grater than Zero as Divisor ")

In [14]:
a=division(5,0)
print(a)

Please enter a number grater than Zero as Divisor 
None


Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

Output should come as below:

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.

In [6]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in subjects:
    for j in verbs:
        for k in objects:
            print( i,j,k,".")

Americans play Baseball .
Americans play Cricket .
Americans watch Baseball .
Americans watch Cricket .
Indians play Baseball .
Indians play Cricket .
Indians watch Baseball .
Indians watch Cricket .


Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1

In [2]:
import numpy as np

def createMatrix(vec):
    """convert the list to Vandermond Matrix"""
    ind=len(vec)
    Metrx=[]
    Holder=[]
    for i in range(len(vec)):#creat the 
        for j in vec:
            k=j**i
            Metrx.append(k)
    while Metrx != []:#Convert list to Matrix
        Holder.append(Metrx[:ind])
        Metrx = Metrx[ind:]
    Result=np.array(Holder)
    return(Result.transpose())

In [3]:
#To test cerateMatrix function
lst=(2,3,4,5)
a=createMatrix(lst)
print(a)

[[  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]
